// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';


function calculateDistance(latitude1, longitude1, latitude2, longitude2, unit) {
  var radianLatitude1 = Math.PI * latitude1 / 180.0;
  var radianLatitude2 = Math.PI * latitude2 / 180.0;
  var radianTheta = Math.PI * (longitude1 - longitude2) / 180.0;
  var distance = Math.sin(radianLatitude1) * Math.sin(radianLatitude2) + Math.cos(radianLatitude1) * Math.cos(radianLatitude2) * Math.cos(radianTheta);
  var distance2 = Math.acos(distance) * (180.0 / Math.PI) * 60.0 * 1.1515;
  var multiplier;
  switch (unit) {
    case "K" : 
        multiplier = 1.609344;
        break;
    case "N" : 
        multiplier = 0.8684;
        break;
    default:
      multiplier = 1.0;
  }
  return distance2 * multiplier;
}

exports.calculateDistance = calculateDistance;
/* No side effect */
